### PR TITLE
GFDL to main (2023-04-06)

### PR DESCRIPTION
**Pull request by marshallward**
This pull request contains several new features and bugfixes, alongside a very large number of commits related to standardization of dimensional analysis.  Despite the size, these should have no impact on any experiments beyond adjustments to configuration parameter files. 

Note that this patch introduces the new netCDF I/O layer to handle simple operations which do not require - or simply do not work with - the FMS I/O layer.  Reviewers should carefully verify any experiments which depend on datasets, particularly anything which may be outside of our standard test suite.

--------

Features
========

- NOAA-GFDL/MOM6#198
- NOAA-GFDL/MOM6#228
- NOAA-GFDL/MOM6#233
- NOAA-GFDL/MOM6#236
- NOAA-GFDL/MOM6#284
- NOAA-GFDL/MOM6#293
- NOAA-GFDL/MOM6#305
- NOAA-GFDL/MOM6#310
- NOAA-GFDL/MOM6#324
- NOAA-GFDL/MOM6#332
- NOAA-GFDL/MOM6#341

Bugfixes
========

- NOAA-GFDL/MOM6#221
- NOAA-GFDL/MOM6#232
- NOAA-GFDL/MOM6#246
- NOAA-GFDL/MOM6#251
- NOAA-GFDL/MOM6#260
- NOAA-GFDL/MOM6#263
- NOAA-GFDL/MOM6#265
- NOAA-GFDL/MOM6#268
- NOAA-GFDL/MOM6#271
- NOAA-GFDL/MOM6#272
- NOAA-GFDL/MOM6#285
- NOAA-GFDL/MOM6#303
- NOAA-GFDL/MOM6#316
- NOAA-GFDL/MOM6#323
- NOAA-GFDL/MOM6#328
- NOAA-GFDL/MOM6#329
- NOAA-GFDL/MOM6#330
- NOAA-GFDL/MOM6#334
- NOAA-GFDL/MOM6#338

Refactor
========

- NOAA-GFDL/MOM6#224
- NOAA-GFDL/MOM6#227
- NOAA-GFDL/MOM6#231
- NOAA-GFDL/MOM6#238
- NOAA-GFDL/MOM6#239
- NOAA-GFDL/MOM6#240
- NOAA-GFDL/MOM6#241
- NOAA-GFDL/MOM6#243
- NOAA-GFDL/MOM6#248
- NOAA-GFDL/MOM6#253
- NOAA-GFDL/MOM6#256
- NOAA-GFDL/MOM6#258
- NOAA-GFDL/MOM6#259
- NOAA-GFDL/MOM6#261
- NOAA-GFDL/MOM6#262
- NOAA-GFDL/MOM6#264
- NOAA-GFDL/MOM6#266
- NOAA-GFDL/MOM6#273
- NOAA-GFDL/MOM6#275
- NOAA-GFDL/MOM6#276
- NOAA-GFDL/MOM6#280
- NOAA-GFDL/MOM6#281
- NOAA-GFDL/MOM6#282
- NOAA-GFDL/MOM6#283
- NOAA-GFDL/MOM6#286
- NOAA-GFDL/MOM6#287
- NOAA-GFDL/MOM6#289
- NOAA-GFDL/MOM6#290
- NOAA-GFDL/MOM6#291
- NOAA-GFDL/MOM6#292
- NOAA-GFDL/MOM6#294
- NOAA-GFDL/MOM6#295
- NOAA-GFDL/MOM6#297
- NOAA-GFDL/MOM6#298
- NOAA-GFDL/MOM6#299
- NOAA-GFDL/MOM6#301
- NOAA-GFDL/MOM6#302
- NOAA-GFDL/MOM6#304
- NOAA-GFDL/MOM6#306
- NOAA-GFDL/MOM6#307
- NOAA-GFDL/MOM6#312
- NOAA-GFDL/MOM6#313
- NOAA-GFDL/MOM6#314
- NOAA-GFDL/MOM6#315
- NOAA-GFDL/MOM6#317
- NOAA-GFDL/MOM6#318
- NOAA-GFDL/MOM6#319
- NOAA-GFDL/MOM6#320
- NOAA-GFDL/MOM6#327
- NOAA-GFDL/MOM6#337

Build/Test
==========

- NOAA-GFDL/MOM6#229
- NOAA-GFDL/MOM6#234
- NOAA-GFDL/MOM6#250
- NOAA-GFDL/MOM6#255
- NOAA-GFDL/MOM6#270
- NOAA-GFDL/MOM6#274
- NOAA-GFDL/MOM6#288
- NOAA-GFDL/MOM6#326

Admin
=====

- NOAA-GFDL/MOM6#226
- NOAA-GFDL/MOM6#242
- NOAA-GFDL/MOM6#252
- NOAA-GFDL/MOM6#257
- NOAA-GFDL/MOM6#309
- NOAA-GFDL/MOM6#322
- NOAA-GFDL/MOM6#325

Contributors:                                                                   
  - @Hallberg-NOAA: 63                                                          
  - @marshallward: 13                                                           
  - @adcroft: 6                                                                 
  - @NoraLoose: 5                                                               
  - @nikizadehgfdl: 2                                                           
  - @awallcraft: 1                                                              
  - @MJHarrison-GFDL: 1                                                         
  - @ashao: 1                                                                   
  - @angus-g: 1                                                                 
  - @andrew-c-ross: 1                                                           
  - @OlgaSergienko: 1

### CODE REVIEW

**Comment by marshallward** [comment]
The MacOS regression tests represent a compilation issue which was unfixed in `main` but has since been fixed in `dev/gfdl` (as indicated by the MacOS stencil tests).

In the future, we will encourage sending these fixes directly to `main` rather than fix them in our respective branches.

**Review by kshedstrom — APPROVED** [review]
I approve this PR.

**Review by abozec — APPROVED** [review]
COAPS approves

**Comment by jiandewang** [comment]
in EMC John Stephen carefully tested it and compared with current N. Atlantic regional setting, final restart files are identical. He also noticed that in output files variables Kv-bkgnd has tiny difference between current and this PR code on the magnitude of   1E-21. Other variables are identical.
For UFS coupled runs, I tested on two R&D machines and they passed our regression test. However it failed in our operational machines regression test due to answer changes (thanks for @DeniseWorthen's help as I am in China now, don't have access to operational machine). I will resume my testing once I am back to US (coming Monday).

**Comment by marshallward** [comment]
@jiandewang I looked at this with @Hallberg-NOAA and we believe that a likely source is the mixed layer restratification.

The diffs in the barotropic solvers are in the halos of the data domain, rather than the compute domain, and are probably due to fixes in the checksum calculations, which had the incorrect halo widths.

The first compute-domain divergence is in `Post-mixedlayer_restrat h`.  We can't say a whole lot without looking at our end, but we found a possible source of divergence:

Old:

https://github.com/mom-ocean/MOM6/blob/1e54bed6ac19799cf6cf2b34c20e914f730a3e3b/src/parameterizations/lateral/MOM_mixed_layer_restrat.F90#L390-L394

New:

https://github.com/mom-ocean/MOM6/blob/fc823f5d71350c48289aa9fd99c7b7fd82de084e/src/parameterizations/lateral/MOM_mixed_layer_restrat.F90#L388-L389

https://github.com/mom-ocean/MOM6/blob/fc823f5d71350c48289aa9fd99c7b7fd82de084e/src/parameterizations/lateral/MOM_mixed_layer_restrat.F90#L824-L826

It's not clear why this could cause a regression, since it's only a refactor, but it's possible that an aggressive compiler could have reordered the multiplication, or moving into a separate function suppressed some undesired optimization.

There is also enough going on in this file that some kind of regression could have happened.

If I get you a modified version of this file without the code change, would you be able to test it?  (Unfortunately it's not as simple as reverting the file, since there was an API change.)

If you have the compiler version and flags used on WCOSS-2, that might also help troubleshoot the problem on our end.

**Comment by jiandewang** [comment]
@marshallward and @Hallberg-NOAA thanks for the quick response, yes I will be able to test if you have a modified file for me. I suspected this commit is the cause but had code conflict when doing revert. Note we have all different setting of MOM in UFS, all of them had this issue except our super coarse resolution (5x5 ocean), in that setting, mixed layer is turned off. I will provide compiling flag shortly

**Comment by jiandewang** [comment]
@marshallward I put compiling output file at /lustre/f2/dev/ncep/Jiande.Wang/MOM6-update/20230406/M6-20230406, see "compiling-output" line 798 for an example of flags being used

**Comment by marshallward** [comment]
Compiler was Intel Fortran 19.1.3, flags are `-g -traceback -i4 -r8 -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -sox  -O2 -debug minimal -fp-model source -module mod`.
This is very close to what we use, so I don't think we can attribute it to compilation.

**Comment by gustavo-marques** [comment]
We are also seeing a change in answers for the CESM tests.

**Comment by marshallward** [comment]
@gustavo-marques Do you know if the diff is in MOM_mixed_layer_restrat?

Also it seems like WCOSS-2 is AMD, is your machine AMD or Intel?

**Comment by marshallward** [comment]
@jiandewang Thanks, that is good news although I think we need to understand what might have caused the fix.  I wonder if it is related to the AMD chipset.

@gustavo-marques I can provide the same modified mixed layer restratification file if you are ready to test it.

**Comment by gustavo-marques** [comment]
> @gustavo-marques Do you know if the diff is in MOM_mixed_layer_restrat?
> 
> Also it seems like WCOSS-2 is AMD, is your machine AMD or Intel?

@marshallward, I have not looked close enough to find out if the difference is coming from MOM_mixed_layer_restrat.
Cheyenne uses Intel.
I am happy to test the modified mixed layer restratification file.
Thanks!

**Comment by marshallward** [comment]
I tested this on C5 (our AMD cluster) but did not detect any regressions.  So it's not a simple matter of Intel vs AMD architecture.  We are using a different compiler from WCOSS (Intel 2022 vs 2019) but unfortunately 2022.02 is all we have available on C5.  We could get into specifics (C5 is EPYC 7H12) but I doubt that is the reason.

It was suggested Monday that there are differences in some layer-remapped diagnostics due to time-space average swapping, but it seems the consensus was that these answer changes are at the lowest bits and are acceptable.  (Anyone please correct me if that is wrong.)

Unfortunately I don't think we have sufficient access to explain this regression, but for now we will revert `MOM_mixed_layer_restrat.F90` and revisit this in the future.

**Review by jiandewang — APPROVED** [review]
with the Reversion of MOM_mixed_layer_restrat growth_time, it passed UFS regression test on wcoss2 and two other R&D machines

**Comment by marshallward** [comment]
The reversion of `MOM_mixed_layer_restrat.F90` was able to preserve the introduction of `u_star_min`, but has deferred the introduction of the `growth_time` function.

**Comment by marshallward** [comment]
@gustavo-marques @sanAkel Any update on this PR?

**Review by sanAkel — APPROVED** [review]
Answers remain same, tests passed!

@marshallward thanks for your patience.

**Comment by gustavo-marques** [comment]
Sorry for the delay. Our tests are passing (no changes in the ocean.stats).
I approve this PR.

**Review by gustavo-marques — APPROVED** [review]

**Comment by marshallward** [comment]
Thanks to all for testing and working through the revisions.

**Pull request merged**
