### PR TITLE
GFDL to main candidate branch (2022-05-16)

### PR DESCRIPTION
**Pull request by marshallward**
This patch includes several new features, as well as the usual crop of bugfixes
and aggressive refactoring.

* Extensive support for the new HybGen/HYCOM vertical grids
* Laplace diffusion of internal heights
* Internal tide: Residual loss term from reflection/transmission
* Ice shelf: surface mass flux (`fluxes%shelf_sfc_mass_flux`)

New parameters

* `VELOCITY_REMAPPING_SCHEME`
* `PARTIAL_CELL_VELOCITY_REMAP`
* `REMAP_VEL_MASK_BBL_THICK`
* `REMAP_VEL_MASK_H_THIN`
* `DATA_OVERRIDE_SHELF_FLUXES`
* `THICKNESS_TOLERANCE`
* `INTERNAL_TIDE_RESIDUAL_DRAG`
* `GME_NUM_SMOOTHINGS`
* `TRANS_FILE`
* `KH_ETA_CONST`
* `KH_ETA_VEL_SCALE`
* HybGen
  * `USE_HYBGEN_UNMIX`
  * `HYBGEN_MIN_THICKNESS`
  * `HYBGEN_N_SIGMA`
  * `HYBGEN_COORD_FILE`
  * `HYBGEN_DEEP_DZ_PR0FILE`
  * `HYBGEN_SHALLOW_DZ_PR0FILE`
  * `HYBGEN_DEEP_DZ_VAR`
  * `HYBGEN_SHALLOW_DZ_VAR`
  * `HYBGEN_TGT_DENSITY_VAR`
  * `HYBGEN_ISOPYCNAL_DZ_MIN`
  * `HYBGEN_MIN_ISO_DEPTH`
  * `HYBGEN_RELAX_PERIOD`
  * `HYBGEN_BBL_THICKNESS`
  * `HYBGEN_REMAP_DENSITY_MATCH`
  * `HYBGEN_REMAP_MAX_ZSTAR_DILATE`
* Legacy reproducibility
  * `ODA_2018_ANSWERS`

New diagnostics

* RK2 (split) dynamic core
  * `deta_dt`
* Horizontal viscosity
  * `d[uv]d[xy]_bt`
* Ice shelf
  * `sfc_mass_flux`
* Internal tides
  * `ITide_tot_residual_loss`
  * `trans`
  * `residual`

Due to the removal of unused variables and whitespace cleanup, this PR is
expected to contain a very large number of changes in total.

Note that the large number of commits (~180) is due to re-introduction of
incorrecltly squashed commits from previous PRs.  Hopefully this will get
everything back on track.

Features
- NOAA-GFDL/MOM6#101: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#99: (@ashao)
- NOAA-GFDL/MOM6#95: (@raphaeldussin)
- NOAA-GFDL/MOM6#89: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#83: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#81: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#80: (@OlgaSergienko)
- NOAA-GFDL/MOM6#77: (@Hallberg-NOAA)

Bugfixes and calculation improvements
- NOAA-GFDL/MOM6#111: (@marshallward)
- NOAA-GFDL/MOM6#106: (@adcroft)
- NOAA-GFDL/MOM6#103: (@herrwang0)
- NOAA-GFDL/MOM6#98: (@NoraLoose)
- NOAA-GFDL/MOM6#90: (@raphaeldussin)
- NOAA-GFDL/MOM6#88: (@raphaeldussin)
- NOAA-GFDL/MOM6#84: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#82: (@marshallward)
- NOAA-GFDL/MOM6#76: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#73: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#69: (@gustavo-marques)
- NOAA-GFDL/MOM6#65: (@gustavo-marques)

Refactoring and testing
- NOAA-GFDL/MOM6#117: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#112: (@marshallward)
- NOAA-GFDL/MOM6#113: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#110: (@marshallward)
- NOAA-GFDL/MOM6#109: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#108: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#107: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#105: (@marshallward)
- NOAA-GFDL/MOM6#104: (@kshedstrom)
- NOAA-GFDL/MOM6#102: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#97: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#96: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#94: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#93: (@marshallward)
- NOAA-GFDL/MOM6#87: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#86: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#85: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#78: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#74: (@marshallward)
- NOAA-GFDL/MOM6#64: (@MJHarrison-GFDL)
- NOAA-GFDL/MOM6#63: (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#49: (@Hallberg-NOAA)

Contributors:
  - @Hallberg-NOAA: 57
  - @marshallward: 16
  - @raphaeldussin: 5
  - @adcroft: 4
  - @MJHarrison-GFDL: 3
  - @kshedstrom: 2
  - @herrwang0: 2
  - @OlgaSergienko: 2
  - @gustavo-marques: 2
  - @wfcooke: 2
  - @ashao: 1
  - @NoraLoose: 1
  - @nikizadehgfdl: 1
  - @laurenchilutti: 1
  - @breichl: 1

### CODE REVIEW

**Comment by marshallward** [comment]
This time with the right branch (Thanks @jiandewang)

Apologies to everyone, those who approved will need to re-approve it.

**Review by kshedstrom — APPROVED** [review]

**Comment by gustavo-marques** [comment]
This candidate is changing answers for some of our tests. We will need some time to investigate this further. 
cc'ing @alperaltuntas 

The candidate merged to dev/ncar can be found [here](https://github.com/gustavo-marques/MOM6/tree/eval_main_candidate_16may2022). There were a lot of conflicts that had to be solved manually.

**Comment by Hallberg-NOAA** [comment]
@gustavo-marques, if find that you are having trouble tracking down why the answers are changing, I may be able to help.

  If you could point us to a git repository with any simple test cases (i.e., not requiring access to huge data volumes or specific access to NCAR machines) where the answers are changing, I might have some time this week to help you track them down.  Moreover, I periodically carry out additional tests beyond those in the standard GFDL pipeline tests, especially before committing some of the more widespread code changes. I would be happy to consider other test cases to add to this list.

**Comment by jiandewang** [comment]
no answer change in UFS and N. Atlantic region setting. I am holding on approval at this moment as @gustavo-marques reported there is answer change in dev/ncar

**Comment by gustavo-marques** [comment]
Thanks, @Hallberg-NOAA. Unfortunately, we do not have any simple test cases that work with the MCT or NUOPC caps.  However, we could put together an ocean-only [global_ALE](https://github.com/NOAA-GFDL/MOM6-examples/tree/dev/gfdl/ocean_only/global_ALE/z) version with the NCAR physics enabled. This is not ideal but could help in identifying changes in answers related to the choice of physics.

**Comment by alperaltuntas** [comment]
@gustavo-marques, unless you have one ready, I have a tx0.66v1 standalone experiment in the following cheyenne directory. I haven't updated it in the last year or so, so you might want to update MOM_input and MOM_override to be able to reproduce the answer change.

/glade/work/altuntas/mom6.standalone.runs/cesm/c.t061.common

And here are the inputs:
/glade/work/altuntas/mom6.standalone.runs/cesm/INPUT/tx0.66v1

**Review by abozec — COMMENTED** [review]
My global ODA test case has passed without a problem but my regional test case has problems with the OBCs and I don't know why it is unhappy about it ... Need to dig a little bit.

**Comment by jiandewang** [comment]
@abozec : following is one of the netcdf file header used by OBC run, it works fine in this PR code
netcdf obc_ts_south {
dimensions:
        nx_segment_002 = 2271 ;
        ny_segment_002 = 1 ;
        nz_segment_002_temp = 50 ;
        nz_segment_002_salt = 50 ;
        time = UNLIMITED ; // (6 currently)
variables:
        int nx_segment_002(nx_segment_002) ;
                nx_segment_002:cartesian_axis = "X" ;
        int ny_segment_002(ny_segment_002) ;
                ny_segment_002:cartesian_axis = "Y" ;
        int nz_segment_002_temp(nz_segment_002_temp) ;
                nz_segment_002_temp:cartesian_axis = "Z" ;
        int nz_segment_002_salt(nz_segment_002_salt) ;
                nz_segment_002_salt:cartesian_axis = "Z" ;
        double time(time) ;
                time:units = "days since 1900-12-31 00:00:00" ;
                time:calendar = "gregorian" ;
        double lon_segment_002(ny_segment_002, nx_segment_002) ;
        double lat_segment_002(ny_segment_002, nx_segment_002) ;
        double ilist_segment_002(ny_segment_002, nx_segment_002) ;
                ilist_segment_002:orientation = 0 ;
        double jlist_segment_002(ny_segment_002, nx_segment_002) ;
                jlist_segment_002:orientation = 0 ;
        double temp_segment_002(time, nz_segment_002_temp, ny_segment_002, nx_segment_002) ;
        double vc_temp_segment_002(time, nz_segment_002_temp, ny_segment_002, nx_segment_002) ;
        double dz_temp_segment_002(time, nz_segment_002_temp, ny_segment_002, nx_segment_002) ;
        double salt_segment_002(time, nz_segment_002_salt, ny_segment_002, nx_segment_002) ;
        double vc_salt_segment_002(time, nz_segment_002_salt, ny_segment_002, nx_segment_002) ;
        double dz_salt_segment_002(time, nz_segment_002_salt, ny_segment_002, nx_segment_002) ;

**Comment by gustavo-marques** [comment]
I was able to track down where answers start to diverge. It's in the [checksum call](https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/parameterizations/lateral/MOM_hor_visc.F90#L1633) for `Ah_h`. The tests passed when `LEITH_AH = False`. Answers are changing with `LEITH_AH = True` because @Hallberg-NOAA correctly change `Del2vort_h` to be rotationally-invariant in https://github.com/NOAA-GFDL/MOM6/commit/ab4d226bb8ea14d58f6176839cc80c56e8ff7b0a

In addition to changing the ocean state, this PR also changes `Total age` (or age stocks) because of the improvements introduced in https://github.com/NOAA-GFDL/MOM6/commit/1bf82205a981fa0ae7390d0e513cdef8315bc23c

Both changes are correct and should be retained. However, I will check with the rest of the NCAR team on how to proceed before approving this PR. I will report back here before Friday EOD.

**Review by gustavo-marques — APPROVED** [review]

**Comment by gustavo-marques** [comment]
We approve this PR.

**Review by jiandewang — APPROVED** [review]

**Review by abozec — APPROVED** [review]
COAPS approves

**Comment by marshallward** [comment]
@sanAkel Are you or Matt able to review this PR?

**Comment by sanAkel** [comment]
> @sanAkel Are you or Matt able to review this PR?

For some reason, I didn't get notified of this PR until now. Will get back in a few hours. Thanks!

**Review by sanAkel — APPROVED** [review]

**Comment by marshallward** [comment]
Everyone has approved this, and it seems like any answer changes are understood and there is a plan to resolve them, so I will now merge this.

Thanks as always to everyone.  Time to update our branches!

**Pull request merged**
