### PR TITLE
initialize cpl_scalar field in nuopc cap

### PR DESCRIPTION
**Pull request by jiandewang**
this mini PR add the initialization of cpl_scalar filed in nuopc cap.

In UFS, it was reported that "Non-CSG components do not use or set the scalar index for NTile. In certain cases, the scalar field value for this index has been found to be non-zero (NaN in debug compiles). " See detail at UFS issue (https://github.com/ufs-community/ufs-weather-model/issues/2369 and https://github.com/ufs-community/ufs-weather-model/issues/2338).

non-CSG= non Cubic Spherical Grid which refers to ocean, ice and wave models in UFS

Thansk for @alperaltuntas for pre-checking of the code change.

### CODE REVIEW

**Review by marshallward — APPROVED** [review]
GFDL approves

**Review by alperaltuntas — APPROVED** [review]
NCAR approves.

**Comment by jiandewang** [comment]
@kshedstrom I guess this PR bypassed your radar, can you review it ?

**Review by kshedstrom — APPROVED** [review]
Sorry, yes, it's been one of those weeks. Yes, I approve, not affecting code I use at all.

**Pull request merged**
