### PR TITLE
Adding the Gradient Model into MOM6

### PR DESCRIPTION
**Pull request by sinakhani**
I would like to request a "pull request review" for a newly added lateral mixing (mesoscale eddy) parameterization into MOM6. Changes are includes in the following files:

1. [MOM_lateral_mixing_coeffs.F90](https://github.com/sinakhani/MOM6/blob/dev/master/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90) 
2. [MOM_thickness_diffuse.F90](https://github.com/sinakhani/MOM6/blob/dev/master/parameterizations/lateral/MOM_thickness_diffuse.F90)
3. [MOM.F90](https://github.com/sinakhani/MOM6/blob/dev/master/core/MOM.F90)

I look forward to working with you on merging these changes. Thank you.

### CODE REVIEW

**Comment by marshallward** [comment]
@sinakhani Could you move this PR to one of the development nodes?  For example:

* https://github.com/NOAA-GFDL/mom6
* https://github.com/NCAR/MOM6/
* ...

Your profile says that you are in Boulder, so perhaps this is in collaboration with NCAR, but if this is independent work then it is probably best handled at NOAA-GFDL.

I am also seeing over 300 changed files, and the PR does not contain any explanation about what has been changed.  At the least, I think you may need to update your code.  I would also suggest you investigate why several of the tests have failed.

**Comment by sinakhani** [comment]
@marshallward I have this PR on my 'main' branch (https://github.com/sinakhani/MOM6/tree/main). My changes include in three .F90 files ([MOM_lateral_mixing_coeffs.F90](https://github.com/sinakhani/MOM6/blob/main/src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90), [MOM_thickness_diffuse.F90](https://github.com/sinakhani/MOM6/blob/main/src/parameterizations/lateral/MOM_thickness_diffuse.F90), and [MOM.F90](https://github.com/sinakhani/MOM6/blob/main/src/core/MOM.F90)). 

Mainly, in MOM_lateral_mixing_coeffs.F90, I have calculated "gradient slopes U_xH_x, etc" as defined in lines 933-978. Then, I calculate the gradient eddy transport diagnostics on u- and v-points in this file. Later, the calculated gradient transports are read in MOM_thickness_diffuse.F90 file to update KH term on u- and v-points. I hope this explanation could help how the new parameterization works.

Also, I am not sure why those tests are failed. I think this is not related to the part of the code I have added. Can I have a meeting with you to make sure that I am doing the "pull request" right? Thank you for your consideration.

**Comment by marshallward** [comment]
@sinakhani What I was trying to say above is that `main` (at mom-ocean/MOM6) is the public release of MOM6.  But all PR contributions must be submitted to the one of the development branches, such as `dev/gfdl`, which is maintained at https://github.com/NOAA-GFDL/MOM6.

PRs from individual contributors are reviewed and merged through the development branch.  The `main` branch only receives updates from these development branches, not individuals.

I am going to close this PR, but I just wanted to clarify that you should re-open it to another fork, most likely https://github.com/NOAA-GFDL/MOM6.

**Comment by marshallward** [comment]
Forgot to add, feel free to reach our to me or others at GFDL, we can talk more about what is needed.

**Pull request closed without merging**
