### PR TITLE
GFDL to main (2022-08-10)

### PR DESCRIPTION
**Pull request by marshallward**
This PR contains two new features, some bugfixes, and an extension of the dimensional scaling to the coupler interfaces ("caps").

We now support an interface to communicate with external databases at runtime.  The current proposal is very strongly designed around SmartRedis, but could be modified and configured to support other database-like systems.

Also included is a new machine learning MEKE solver which uses this database interface.

Reproducibility of legacy solvers can now be managed by an ANSWER_DATE parameter.  Older flags such as ANSWERS_2018 are still supported, but can now be automatically configured by ANSWER_DATE.

Note that this patch contains changes to the driver and coupler code related to dimensional scaling, and should be reviewed carefully by anyone using them.

Also note that the git submodules to CVMix and GSW (TEOS) now point to repositories under mom-ocean, rather than the parent repositories.  Source code and git hashes are equivalent, so no changes are required.

Features
========
- NOAA-GFDL/MOM6#159 (@ashao)
- NOAA-GFDL/MOM6#179 (@Hallberg-NOAA)

Bugfix
======
- NOAA-GFDL/MOM6#170 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#171 (@kshedstrom)
- NOAA-GFDL/MOM6#176 (@awallcraft)

Refactor
========
- NOAA-GFDL/MOM6#167 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#172 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#175 (@marshallward)
- NOAA-GFDL/MOM6#180 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#181 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#182 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#183 (@Hallberg-NOAA)

Meta
====
- NOAA-GFDL/MOM6#174 (@adcroft)
- NOAA-GFDL/MOM6#178 (@marshallward)
- NOAA-GFDL/MOM6#185 (@marshallward)
- NOAA-GFDL/MOM6#187 (@marshallward)
- NOAA-GFDL/MOM6#191 (@marshallward)

Contributors:
  - @Hallberg-NOAA: 8
  - @marshallward: 5
  - @awallcraft: 1
  - @adcroft: 1
  - @kshedstrom: 1
  - @ashao: 1

### CODE REVIEW

**Review by kshedstrom — APPROVED** [review]

**Review by abozec — APPROVED** [review]
COAPS approves, it passed our 2 tests.

**Comment by jiandewang** [comment]
works fine in UFS and N. Atlantic regional setting.

**Review by jiandewang — APPROVED** [review]

**Review by alperaltuntas — APPROVED** [review]
NCAR tests (inc. dimensional consistency tests) are passing. No answer changes.

**Review by sanAkel — APPROVED** [review]
Preserves answers within GEOS (@marshallward, thanks for waiting and being patient!).

**Comment by marshallward** [comment]
Thanks everyone, I will merge this now.

**Comment by marshallward** [comment]
Since the `build-test-nans` test has been renamed to `build-coverage`, this test will never run.  I've removed `build-test-nans` from the list of required tests, but it still seems to be required.

If I can't figure out how to re-run these tests, I will do an admin override.

**Pull request merged**
