### PR TITLE
dev emc candidate 20230122

### PR DESCRIPTION
**Pull request by jiandewang**
This PR contains two NUOPC cap enhancements:
(1) switch to cesm style field names so that field names were aligned with those in https://github.com/ESCOMP/CMEPS/blob/main/mediator/fd_cesm.yaml (see detail at https://github.com/NOAA-EMC/MOM6/pull/120)

(2) add non-interval restart writing capability: this requirement is from EMC DA group which requires to write out restart files at irregular time frequency. (see detail at https://github.com/ufs-community/ufs-weather-model/issues/1976)

both of the them have been pre-tested from NCAR side (thanks @alperaltuntas)

### CODE REVIEW

**Review by sanAkel — APPROVED** [review]
Changes are outside the scope of FMS driver - hence do not impact GEOS applications.

Having said that, fyi, in GEOS coupled model, restart can be written out at any desired frequency using [this](https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/25333342ffd66f789cf0a83ad84a89d32c7ab342/MOM6_GEOSPlug/MOM6_GEOSPlug.F90#L1100-L1119).

**Review by marshallward — APPROVED** [review]
Looks OK; nothing we depend directly upon.

**Review by abozec — APPROVED** [review]
No changes for us. COAPS approves.

**Comment by jiandewang** [comment]
> Changes are outside the scope of FMS driver - hence do not impact GEOS applications.
> 
> Having said that, fyi, in GEOS coupled model, restart can be written out at any desired frequency using [this](https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/25333342ffd66f789cf0a83ad84a89d32c7ab342/MOM6_GEOSPlug/MOM6_GEOSPlug.F90#L1100-L1119).

@sanAkel thanks for the information.

**Review by kshedstrom — APPROVED** [review]
My tests don't depend on this code either.

**Comment by alperaltuntas** [comment]
I am currently testing this pr. There appears to be a small but consistent slow down ( 2-3%) that I am trying to track down. Will keep you updated.

**Review by alperaltuntas — APPROVED** [review]
all good.

**Comment by jiandewang** [comment]
thanks for everbody's time and effect, I am going to merge this to main.

**Pull request merged**
