### PR TITLE
Add river forcing with adjustable depth range condition for user-set diffusivity in  MOM6

### PR DESCRIPTION
**Pull request by Subrat-Kumar-Mallick**
The modification made here enhance control over diffusivity setting in MOM6. By incorporating river forcing and an adjustable depth range condition in the **user_change_diffusivity.F90** file, user can now fine-tune diffusivity parameters based on specific depth ranges and runoff values, improving the model's accuracy in simulating oceanic processes affected by external forcing near the river mouth.

### CODE REVIEW

**Comment by marshallward** [comment]
Hi @Subrat-Kumar-Mallick, do you know if COAPS has its own fork to direct PRs to the main branch?  That is how it is supposed to work, although I believe we have taken PRs directly from @abozec in the past, so perhaps we can do the same here.

**Comment by abozec** [comment]
Hi @marshallward, no we don't have a special fork at COAPS, since it is usually me or @awallcraft  doing the PRs...

**Comment by marshallward** [comment]
After talking with @abozec, we decided that it might be easier to handle this (and perhaps future COAPS PRs) through the NOAA-GFDL fork, and to address some of the specific issues when @Subrat-Kumar-Mallick becomes available to work on them.

Closing this for now, but we will certainly revisit this one soon.

**Comment by Subrat-Kumar-Mallick** [comment]
Hi @marshallward, thank you for the response and discussion regarding my pull request.
I understand and respect the decision to handle this and future COAPS pull requests through the NOAA-GFDL fork.
Given this I would like to withdraw my current pull request.

Thank you for your understanding and consideration.

**Pull request closed without merging**
