### PR TITLE
GFDL to main 2024-05-16

### PR DESCRIPTION
**Pull request by marshallward**
Once again, GFDL is submitting a truckload of PRs to the main branch.  There are several new features and bugfixes, but they are diverse enough that I should probably let them speak for themselves.

With regards to testing, the intermittent failures in documentation, code coverage and (so-called) performance testing ought to be fixed now. :crossed_fingers: 

Thanks to @Hallberg-NOAA for organizing this batch (not to mention the dozens of contributions!)

Features
--------
- NOAA-GFDL/MOM6#614 (@kshedstrom)
- NOAA-GFDL/MOM6#608 (@claireyung)
- NOAA-GFDL/MOM6#606 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#599 (@adcroft)
- NOAA-GFDL/MOM6#585 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#579 (@herrwang0)
- NOAA-GFDL/MOM6#576 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#557 (@marshallward)
- NOAA-GFDL/MOM6#555 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#545 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#544 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#543 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#541 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#538 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#534 (@Hallberg-NOAA)

Bugfixes
--------
- NOAA-GFDL/MOM6#627 (@marshallward)
- NOAA-GFDL/MOM6#620 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#618 (@alex-huth)
- NOAA-GFDL/MOM6#604 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#595 (@adcroft)
- NOAA-GFDL/MOM6#593 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#584 (@marshallward)
- NOAA-GFDL/MOM6#582 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#581 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#580 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#577 (@yichengt900)
- NOAA-GFDL/MOM6#573 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#572 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#570 (@marshallward)
- NOAA-GFDL/MOM6#566 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#565 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#562 (@wfcooke)
- NOAA-GFDL/MOM6#560 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#558 (@marshallward)
- NOAA-GFDL/MOM6#540 (@kshedstrom)
- NOAA-GFDL/MOM6#531 (@kshedstrom)
- NOAA-GFDL/MOM6#527 (@alex-huth)
- NOAA-GFDL/MOM6#520 (@kshedstrom)

Non-Boussinesq fixes (+Boussinesq refactoring)
----------------------------------------------
- NOAA-GFDL/MOM6#588 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#587 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#556 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#554 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#553 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#552 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#549 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#547 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#546 (@Hallberg-NOAA)

Diagnostics
-----------
- NOAA-GFDL/MOM6#605 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#568 (@marshallward)
- NOAA-GFDL/MOM6#567 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#564 (@Hallberg-NOAA)

Input parameter handling
------------------------
- NOAA-GFDL/MOM6#536 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#535 (@Hallberg-NOAA)

Refactoring
-----------
- NOAA-GFDL/MOM6#591 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#548 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#537 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#524 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#522 (@adcroft)

Variable documentation
----------------------
- NOAA-GFDL/MOM6#601 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#597 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#592 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#586 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#569 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#561 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#559 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#528 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#525 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#523 (@Hallberg-NOAA)

Build system
------------
- NOAA-GFDL/MOM6#632 (@marshallward)
- NOAA-GFDL/MOM6#626 (@marshallward)
- NOAA-GFDL/MOM6#600 (@marshallward)
- NOAA-GFDL/MOM6#596 (@marshallward)
- NOAA-GFDL/MOM6#594 (@marshallward)
- NOAA-GFDL/MOM6#578 (@marshallward)
- NOAA-GFDL/MOM6#575 (@adcroft)
- NOAA-GFDL/MOM6#551 (@ashjbarnes)
- NOAA-GFDL/MOM6#533 (@marshallward)

Code maintenance
----------------
- NOAA-GFDL/MOM6#630 (@marshallward)
- NOAA-GFDL/MOM6#598 (@marshallward)
- NOAA-GFDL/MOM6#571 (@marshallward)

Contributors
------------
- @Hallberg-NOAA: 49
- @marshallward: 16
- @kshedstrom: 4
- @adcroft: 4
- @alex-huth: 2
- @claireyung: 1
- @herrwang0: 1
- @yichengt900: 1
- @wfcooke: 1
- @ashjbarnes: 1

### CODE REVIEW

**Comment by marshallward** [comment]
AFAIK these regressions are expected.  These are due to introduction of the bit-reproducible cube root function, and rewrite of certain diagnostics to make them rotationally symmetric, in preparation for FMA-reproducibility.

* NOAA-GFDL/MOM6#541
* NOAA-GFDL/MOM6#545
* NOAA-GFDL/MOM6#605

However, I really do not have a clue where these MacOS errors came from:
```
   internal compiler error: in gfc_walk_array_ref, at fortran/trans-array.cc:11870
  Please submit a full bug report, with preprocessed source (by using -freport-bug).
  See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
  make[2]: *** [netcdf_io.o] Error 1
  make[1]: *** [fms/build/libFMS.a] Error 2
  make: *** [build/deps/lib/libFMS.a] Error 2
```
I haven't seen this before.  I hope that it's temporary.

**Comment by Hallberg-NOAA** [comment]
Depending on how `DEFAULT_ANSWER_DATE` is set, in order to recover the previous solutions you might need to explicitly set `ML_RESTRAT_ANSWER_DATE = 20231231` (or lower) (for NOAA-GFDL/MOM6#545) and `EPBL_ANSWER_DATE = 20231231` or lower (for NOAA-GFDL/MOM6#541) to recover the previous solutions.  The change to using reproducible answers in the diagnostics in NOAA-GFDL/MOM6#605 can not be robustly recovered for any set of parentheses, and given that these diagnostics differ from before only at round-off, we opted not to provide a run-time flag to recover the previous answers.  So, yes, depending on `DEFAULT_ANSWER_DATE` is set there are expected regressions.  There are also expected regressions with fully non-Boussnesq configurations, but the nobody-is-using-it-yet exception that allows this will be ending very soon.

  By contrast, the MacOS compiler time failures were not expected.

**Comment by marshallward** [comment]
This does not appear to be about MacOS but rather about GFortran 14.1.  I reproduced this on my home machine:
```
mpifort -DPACKAGE_NAME=\"FMS\" -DPACKAGE_TARNAME=\"fms\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"FMS\" -DPACKAGE_BUGREPORT=\"https://github.com/NOAA-GFDL/FMS/issues\" -DPACKAGE_URL=\"\" -DHAVE_MPI=1 -DHAVE_GETTID=1 -DHAVE_SCHED_GETAFFINITY=1 -DHAVE_MPI=1 -Duse_libMPI=1 -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_NETCDF_H=1 -Duse_netCDF=1 -g -O0 -fcray-pointer -fdefault-real-8 -fdefault-double-8 -fallow-invalid-boz -fallow-argument-mismatch  -c ../src/fms2_io/netcdf_io.F90 -I../src/fms2_io/include
register_variable_attribute.inc:56:60:

internal compiler error: in gfc_walk_array_ref, at fortran/trans-array.cc:11870
0x1ffd19a internal_error(char const*, ...)
	???:0
0x6f365f fancy_abort(char const*, int, char const*)
	???:0
0x844964 gfc_walk_expr(gfc_expr*)
	???:0
0x884767 gfc_conv_procedure_call(gfc_se*, gfc_symbol*, gfc_actual_arglist*, gfc_expr*, vec<tree_node*, va_gc, vl_embed>*)
	???:0
0x8833b3 gfc_conv_expr_reference(gfc_se*, gfc_expr*)
	???:0
0x886ed3 gfc_conv_procedure_call(gfc_se*, gfc_symbol*, gfc_actual_arglist*, gfc_expr*, vec<tree_node*, va_gc, vl_embed>*)
	???:0
0x8d252c gfc_trans_block_construct(gfc_code*)
	???:0
0x8c7980 gfc_trans_select_type(gfc_code*)
	???:0
0x8d252c gfc_trans_block_construct(gfc_code*)
	???:0
0x8c0caa gfc_trans_if(gfc_code*)
	???:0
0x87dcd7 gfc_generate_function_code(gfc_namespace*)
	???:0
0x839c89 gfc_generate_module_code(gfc_namespace*)
	???:0
0x7f1c4f gfc_parse_file()
	???:0
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/issues> for instructions.
make[2]: *** [Makefile.dep:235: netcdf_io.o] Error 1
make[2]: Leaving directory '/home/marshall/gfdl/mom6/.testing/deps/fms/build'
make[1]: *** [Makefile:45: fms/build/libFMS.a] Error 2
make[1]: Leaving directory '/home/marshall/gfdl/mom6/.testing/deps'
make: *** [Makefile:342: deps/lib/libFMS.a] Error 2
```
I don't think this is a MOM6 issue.  It just happens that our MacOS image is using a newer version than our Ubuntu image.

**Comment by marshallward** [comment]
Although I don't think this is really an FMS problem, I have opened the issue with them: 

https://github.com/NOAA-GFDL/FMS/issues/1527

I suppose we can either pray that GCC pushes an emergency fix (unlikely), or get FMS to release a modified version which works around the problem.  This might require a new patch to MOM6 pointing to this new version.

... assuming that the new version works without any issues.

**Pull request closed without merging**
