### PR TITLE
dev-emc-candidate 20240521 (end of run restart file)

### PR DESCRIPTION
**Pull request by jiandewang**
this PR (original author: Daniel Sarmiento @dpsarmie) will allow UFS to write out restart file for MOM6 (and all other UFS components) at the end of the run using the write_restart_at_endofrun configuration option at the top level in CMEPS. The only file being changed is nuopc_cap. Thanks @alperaltuntas for pre-test and code review.

### CODE REVIEW

**Review by kshedstrom — APPROVED** [review]
As this only changes the nuopc cap, I am not in a position to test it.

**Review by sanAkel — APPROVED** [review]
Same comment as @kshedstrom

**Review by marshallward — APPROVED** [review]
GFDL approves

**Comment by marshallward** [comment]
Actually, I may need to rescind that approval.  You most likely need to address this issue:
```
Run grep "warning:" docs/_build/doxygen_warn_nortd_log.txt | grep -v "as part of a" | tee doxy_errors
config_src/drivers/nuopc_cap/mom_cap.F90, line 386: Line length exceeded "  call NUOPC_CompAttributeGet(gcomp, name="write_restart_at_endofrun", value=value, isPresent=isPresent, isSet=isSet, rc=rc)"
```
The line length needs to be fixed.

**Comment by jiandewang** [comment]
> Actually, I may need to rescind that approval. You most likely need to address this issue:
> 
> ```
> Run grep "warning:" docs/_build/doxygen_warn_nortd_log.txt | grep -v "as part of a" | tee doxy_errors
> config_src/drivers/nuopc_cap/mom_cap.F90, line 386: Line length exceeded "  call NUOPC_CompAttributeGet(gcomp, name="write_restart_at_endofrun", value=value, isPresent=isPresent, isSet=isSet, rc=rc)"
> ```
> 
> The line length needs to be fixed.

sorry this bypassed my radar. Just fixed that

**Comment by marshallward** [comment]
> sorry this bypassed my radar. Just fixed that

I'd say it's perfectly understandable, given there are three other largely unfixable tests.

We could send those fixes as cherry-picked commits, but they are also in the upcoming GFDL PR, so they should be resolved soon enough.  (Unfortunately our PR has become a bit delayed, but will hopefully be in very soon.)

**Review by abozec — APPROVED** [review]
Does not affect us so I approve.

**Review by alperaltuntas — APPROVED** [review]

**Pull request merged**
