### PR TITLE
GFDL to main (2024-05-31)

### PR DESCRIPTION
**Pull request by marshallward**
Redo of #1627, I will try to keep it brief.  This should finalize most of the necessary Nonboussinesq support.  It should also include an important update to enable the latest FMS library (2024+) but YMMV.

Many other new features and bugfixes, please peruse the PR list below.

Features
--------
- NOAA-GFDL/MOM6#614 (@kshedstrom)
- NOAA-GFDL/MOM6#608 (@claireyung)
- NOAA-GFDL/MOM6#606 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#599 (@adcroft)
- NOAA-GFDL/MOM6#585 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#579 (@herrwang0)
- NOAA-GFDL/MOM6#576 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#557 (@marshallward)
- NOAA-GFDL/MOM6#555 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#545 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#544 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#543 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#541 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#538 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#534 (@Hallberg-NOAA)

Bugfixes
--------
- NOAA-GFDL/MOM6#650 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#649 (@breichl)
- NOAA-GFDL/MOM6#628 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#627 (@marshallward)
- NOAA-GFDL/MOM6#624 (@MJHarrison-GFDL)
- NOAA-GFDL/MOM6#620 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#618 (@alex-huth)
- NOAA-GFDL/MOM6#609 (@claireyung)
- NOAA-GFDL/MOM6#604 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#595 (@adcroft)
- NOAA-GFDL/MOM6#593 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#584 (@marshallward)
- NOAA-GFDL/MOM6#582 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#581 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#580 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#577 (@yichengt900)
- NOAA-GFDL/MOM6#573 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#572 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#570 (@marshallward)
- NOAA-GFDL/MOM6#566 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#565 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#562 (@wfcooke)
- NOAA-GFDL/MOM6#560 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#558 (@marshallward)
- NOAA-GFDL/MOM6#540 (@kshedstrom)
- NOAA-GFDL/MOM6#531 (@kshedstrom)
- NOAA-GFDL/MOM6#527 (@alex-huth)
- NOAA-GFDL/MOM6#520 (@kshedstrom)

Non-Boussinesq fixes (+Boussinesq refactoring)
----------------------------------------------
- NOAA-GFDL/MOM6#610 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#588 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#587 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#556 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#554 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#553 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#552 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#549 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#547 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#546 (@Hallberg-NOAA)

Diagnostics
-----------
- NOAA-GFDL/MOM6#605 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#568 (@marshallward)
- NOAA-GFDL/MOM6#567 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#564 (@Hallberg-NOAA)

Input parameter handling
------------------------
- NOAA-GFDL/MOM6#536 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#535 (@Hallberg-NOAA)

Refactoring
-----------
- NOAA-GFDL/MOM6#637 (@uramirez8707)
- NOAA-GFDL/MOM6#612 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#602 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#591 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#548 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#537 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#524 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#522 (@adcroft)

Variable documentation
----------------------
- NOAA-GFDL/MOM6#651 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#601 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#597 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#592 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#586 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#569 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#561 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#559 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#528 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#525 (@Hallberg-NOAA)
- NOAA-GFDL/MOM6#523 (@Hallberg-NOAA)

Build system
------------
- NOAA-GFDL/MOM6#655 (@marshallward)
- NOAA-GFDL/MOM6#652 (@marshallward)
- NOAA-GFDL/MOM6#647 (@marshallward)
- NOAA-GFDL/MOM6#642 (@adcroft)
- NOAA-GFDL/MOM6#632 (@marshallward)
- NOAA-GFDL/MOM6#626 (@marshallward)
- NOAA-GFDL/MOM6#600 (@marshallward)
- NOAA-GFDL/MOM6#596 (@marshallward)
- NOAA-GFDL/MOM6#594 (@marshallward)
- NOAA-GFDL/MOM6#578 (@marshallward)
- NOAA-GFDL/MOM6#575 (@adcroft)
- NOAA-GFDL/MOM6#551 (@ashjbarnes)
- NOAA-GFDL/MOM6#533 (@marshallward)

Code maintenance
----------------
- NOAA-GFDL/MOM6#630 (@marshallward)
- NOAA-GFDL/MOM6#598 (@marshallward)
- NOAA-GFDL/MOM6#571 (@marshallward)

Contributors
------------
- @Hallberg-NOAA: 49
- @marshallward: 16
- @kshedstrom: 4
- @adcroft: 4
- @alex-huth: 2
- @claireyung: 1
- @herrwang0: 1
- @yichengt900: 1
- @wfcooke: 1
- @ashjbarnes: 1

### CODE REVIEW

**Review by kshedstrom — APPROVED** [review]
I approve this PR.

**Comment by jiandewang** [comment]
I am getting error: FATAL from PE     0: diag_manager_mod::diag_send_complete: diag_manager_set_time_end must be called before diag_send_complete

in UFS we are using FMS 2023.04
I guess this is related to https://github.com/mom-ocean/MOM6/pull/1631/commits/7305528fd99bc09bda648693cd7130e4627de25c

**Comment by marshallward** [comment]
@jiandewang Can you see what happens with 2024.01 or 2024.01.01?  We may need to start fine-tuning our `config_src/infra` directory.

**Comment by jiandewang** [comment]
@marshallward it is not too straightforward to switch FMS version as in UFS FMS is used as a pre-build library. Let me try to seek help from EMC internal to see if they can give me some guidance on how to do this.

**Comment by marshallward** [comment]
In that case let me try to see if I can replicate the problem.  I have also reached out to @uramirez8707 to see if he recognizes the problem.

**Comment by marshallward** [comment]
@jiandewang it looks like the way to fix this is to add `call diag_manager_set_time_end(Time_end)` to your drivers, in the same way that diag_manager_set_time_end_infra(Time_end)` was added to the ocean-only and ice-shelf drivers.

It should be backwards compatible with older FMS versions (at least back to 2019), but I'm not sure how easy it is for you to make this modification to your drivers.  I'll get in touch with you about it.

**Comment by marshallward** [comment]
We got together at GFDL to discuss this change and decided that placing `disable_averaging()` inside of `diag_send_complete()` could lead to potential performance problems that we wish to avoid.  We will need a bit of time to work out the proper place for this call, so for now we have removed it from `disable_averaging()`, which should fix the error you are seeing.

In the meantime, I would suggest looking in whether it is possible to add `diag_manager_set_time_end()` calls to your drivers/couplers in order to support `diag_send_complete()` calls.  I'm not sure how this will evolve, but for now it is not possible to call `diag_send_complete()` unless the final time is set in the diag manager.

**Comment by jiandewang** [comment]
@marshallward your updated code allows UFS jobs to run. Can you confirm with me that there is a new variable "h_ML" being added to the restart file ?

**Comment by marshallward** [comment]
@jiandewang Yes this was the commit: c3002089f9255351c599b7c197027ee128ce6a0b

And this was the PR: https://github.com/NOAA-GFDL/MOM6/pull/610

**Comment by jiandewang** [comment]
@marshallward 
(1) all jobs failed to retain current baseline except "debug" cases on wcoss2, apparently FMA related.
(2) super coarse resolution (5x5) faiiled to retain baseline on all machines.

Let me dive in to narrow down the issue (1) for you. Issue (2) is not a critical one as we use this case for IT purpose so let's focus on (1) at this moment

one help from you before I start to work: in this PR there are two new files being added, can you point me which commit did this happen ?
 create mode 100644 src/core/MOM_dynamics_split_RK2b.F90
 create mode 100644 src/equation_of_state/MOM_EOS_base_type.F90

**Comment by marshallward** [comment]
I'll answer the easy one:

> in this PR there are two new files being added, can you point me which commit did this happen ?
> create mode 100644 src/core/MOM_dynamics_split_RK2b.F90
> create mode 100644 src/equation_of_state/MOM_EOS_base_type.F90

```
$ git log --oneline --diff-filter=A -- src/core/MOM_dynamics_split_RK2b.F90 src/equation_of_state/MOM_EOS_base_type.F90
```
2ea0ac32d +Add MOM_dynamics_split_RK2b enabled by SPLIT_RK2B
d8579d292 Use a class to deliver elemental procedures for EOS

I'll try to look into the other issues.  If it's FMA related then we should be able to detect it.

**Comment by jiandewang** [comment]
@marshallward can you confirm with me that https://github.com/mom-ocean/MOM6/pull/1631/commits/d8579d2922a5807955ba40fccb0550707e772823 is the first commit for this PR ?

**Comment by marshallward** [comment]
> @marshallward can you confirm with me that [d8579d2](https://github.com/mom-ocean/MOM6/commit/d8579d2922a5807955ba40fccb0550707e772823) is the first commit for this PR ?

Yes, it's the first commit.

**Comment by jiandewang** [comment]
my test shows the first commit https://github.com/mom-ocean/MOM6/commit/d8579d2922a5807955ba40fccb0550707e772823 changed UFS baseline for both regular and debug jobs. Debug job answer matchs UFS baseline when I run with the last commit (https://github.com/mom-ocean/MOM6/pull/1631/commits/0578393e48d7ee3bb73b01072146b57f59b469eb) of this PR so it got corrected in the middle of this PR. However for regular jobs the results from the first commit are different from the last commit(https://github.com/mom-ocean/MOM6/pull/1631/commits/0578393e48d7ee3bb73b01072146b57f59b469eb) so there must be at least another one commit that changed the sanwer again. I will do more test to narrow down the issue.

**Comment by Hallberg-NOAA** [comment]
@jiandewang, it might be helpful to compare the MOM_parameter_doc files for your super-coarse resolution (5x5) runs whose answers changed on all machines, to see whether they give us some indication of whether the code modifications that changed your answers might be related to an inadvertent change in parameter defaults.

**Comment by jiandewang** [comment]
@Hallberg-NOAA for 5x5 case MOM*doc are identical. See GAEA /gpfs/f5/nggps_emc/scratch/Jiande.Wang/For-Marshall/PR0608/5x5. I also put run log here.
differences start at

212,215c212,215
< 12: u-point: mean=   3.2307571208876769E-03 min=  -5.8371927514297250E-01 max=   4.7912361243792878E-01 u Before steps forces%tau[xy]
< 12: u-point: c=     59358 W=     59358 u Before steps forces%tau[xy]
< 12: v-point: mean=  -8.7648736000826377E-04 min=  -3.8460667960239331E-01 max=   4.5182482367100424E-01 v Before steps forces%tau[xy]
< 12: v-point: c=     61483 S=     59487 v Before steps forces%tau[xy]
---
> 12: u-point: mean=   3.2305299969349007E-03 min=  -5.8371927514312683E-01 max=   4.7912361243809076E-01 u Before steps forces%tau[xy]
> 12: u-point: c=     59489 W=     59489 u Before steps forces%tau[xy]
> 12: v-point: mean=  -8.7690215147357255E-04 min=  -3.8460667960314354E-01 max=   4.5182482396839752E-01 v Before steps forces%tau[xy]
> 12: v-point: c=     61482 S=     59470 v Before steps forces%tau[xy]

**Comment by gustavo-marques** [comment]
This PR is also changing answers for the CESM tests.

Diffing MOM_parameter_doc.all, I see that

```TRIG_CHANNEL_DRAG_WIDTHS = True``` (default)

Should this be set to `false` by default? 

I still get changes in answers when ```TRIG_CHANNEL_DRAG_WIDTHS = False```.  

First major differences in the log file with DEBUG=True:

**dev/ncar**
```
dec0041.hsn.de.hpc.ucar.edu 128: u-point: mean=   4.5580567587152187E-07 min=   0.0000000000000000E+00 max=   6.6911668150526089E-03 u Ray [uv]
dec0041.hsn.de.hpc.ucar.edu 128: u-point: c=  64713534 u Ray [uv]
dec0041.hsn.de.hpc.ucar.edu 128: v-point: mean=   5.0431699077425714E-07 min=   0.0000000000000000E+00 max=   3.7254268231521775E-03 v Ray [uv]
dec0041.hsn.de.hpc.ucar.edu 128: v-point: c=  67226942 v Ray [uv]
```

**This PR**
```
dec0770.hsn.de.hpc.ucar.edu 128: u-point: mean=   4.5580567587152171E-07 min=   0.0000000000000000E+00 max=   6.6911668150526089E-03 u Ray [uv]
dec0770.hsn.de.hpc.ucar.edu 128: u-point: c=  64711494 u Ray [uv]
dec0770.hsn.de.hpc.ucar.edu 128: v-point: mean=   5.0431699077425703E-07 min=   0.0000000000000000E+00 max=   3.7254268231521775E-03 v Ray [uv]
dec0770.hsn.de.hpc.ucar.edu 128: v-point: c=  67226380 v Ray [uv]
```

**Comment by marshallward** [comment]
@gustavo-marques Did you test the most recent version?  I updated the branch about 3 days ago.

I believe that you want `TRIG_CHANNEL_DRAG_WIDTHS` to be true.  This uses the legacy solver which relies on trigonometric functions.  (False is expected to change answers.)

**Comment by gustavo-marques** [comment]
@marshallward thanks! No, that was before your latest update. 

I've updated the branch and set TRIG_CHANNEL_DRAG_WIDTHS=True.
Still getting different answers.

dev/ncar:
```
dec0041.hsn.de.hpc.ucar.edu 128: h-point: mean=   2.5448140050659184E-03 min=   0.0000000000000000E+00 max=   9.3739244659567755E-01 before KPP_applyNLT NLTheat
```
This PR:
```
dec0072.hsn.de.hpc.ucar.edu 128: h-point: mean=   6.6809750932467557E+02 min=   0.0000000000000000E+00 max=   6.0000000000000000E+03 before KPP_applyNLT NLTheat
```

**Comment by marshallward** [comment]
That looks different, did it fix the `[uv] Ray` diff?

**Comment by gustavo-marques** [comment]
Yes, it did!

**Comment by marshallward** [comment]
That is interesting.  The latest patch should only have fixed FMA reproducibility issues in the BBL.  Does it mean that your test is using FMAs?

As for the newest diff, I am not sure what to say other than it is in `MOM_diabatic_driver.F90` (and it's related to KPP, of course).  Maybe you could send me your `MOM_input` and/or `MOM_parameter_doc.all` and I could try to replicate it here.

**Comment by gustavo-marques** [comment]
I don't know if we're using FMAs, but I see that we use the "-no-fma" flag. Yes, I will send you our MOM_input and MOM_parameter_doc.all. Thanks!

**Comment by marshallward** [comment]
We have two PRs to the PR which may help to address the above issues:
* https://github.com/NOAA-GFDL/MOM6/pull/678 
* https://github.com/NOAA-GFDL/MOM6/pull/679

The first introduces a new MOM_input parameter, `USE_HUYNH_STENCIL_BUG`, which uses the old tracer advection stencil.

The second restores the zero-initialization of various fields in the KPP solver, which may have accounted for the differences in checksums.

Note that they have not yet been added to the PR, but if @jiandewang and @gustavo-marques are able to test them and they work, then we can add them.

**Comment by gustavo-marques** [comment]
@marshallward and @Hallberg-NOAA, thanks for helping to address these issues. 

I've merged the two PRs and, unfortunately, I am still getting changes in answers. Now in `calc_Eady_growth_rate_2D dzS2N2[uv]`.

PR:
`u-point: mean=  3.8428083583413220E-05 min=  0.0000000000000000E+00 max=  1.2641506534851180E-01 u calc_Eady_growth_rate_2D dzS2N2[uv]`

dev/ncar:
` u-point: mean=  3.8427337575902537E-05 min=  0.0000000000000000E+00 max=  1.2641506512648903E-01 u calc_Eady_growth_rate_2D dzS2N2[uv]`

**Comment by jiandewang** [comment]
@marshallward some further testing results from EMC
(1) USE_HUYNH_STENCIL_BUG=T solved the wcoss2 problem, the results match current UFS baseline now.
(2) USE_HUYNH_STENCIL_BUG has no impact on results on HERA, results are identical whether it is T or F, kind of puzzled here
(3) KPP PR caused DEBUG-gnu job hanging on HERA (note we don't test gnu on wcoss2), DEBUG-intel job runs fine. Seems memory related issue:
     _WARNING: Open MPI failed to TCP connect to a peer MPI process.  This
  should not happen.

 Your Open MPI job may now hang or fail.

 Local host: h11c27
 PID:        3783435
 Message:    connect() to [10.184.11.22:1032](http://10.184.11.22:1032/) failed
 Error:      Resource temporarily unavailable (11)
124: [h11c34][[9369,0],124][../../../../../opal/mca/btl/tcp/btl_tcp.c:559:mca_btl_tcp_recv_blocking] recv(432) failed: Connection reset by peer (104)_

(4) repeat (3) but on HERCULES (a machine with 192G momery per node, two times as much as HERA), DEBUG-gnu job runs fine
(5) repeat (3) on HERA but only use half of CPU on each node, DEBUG-gnu job runs fine
(6) 5x5 super coarse jobs failed to match UFS baseline on all machines (not really a critical issue as this setting is used for IT test purpose only)

**Comment by marshallward** [comment]
@jiandewang thank you for checking this so comprehensively.  At the very least, it seems that we can merge https://github.com/NOAA-GFDL/MOM6/pull/678 into the PR.

I am unsure what to think about the other error that you are seeing.  It does not look like a memory error to me, but an MPI error.  But assuming your tests are reproducible, then it does seem plausible.

I suppose that some `.bss` thing could be happening (or not happening) after the zero initialization.  Are you running with unlimited stack size?  Normally we do not need this.

Either way, maybe we should reconsider the move from heap to stack and simply undo the entire change.

**Comment by jiandewang** [comment]
@marshallward yes the memory issue is reprodutiable. Initially I thought it was our machine or library issue but after I tried UFS current baseline code, it turned out that this issue doesn't exist in MOM6 main repo code. I repeated the run 4 times at different times and got the same issue.

**Comment by marshallward** [comment]
@jiandewang Can you confirm the stacksize limits of the debug-gnu job?  (`ulimit -s` in bash, `limit stacksize` in tcsh).

**Comment by jiandewang** [comment]
@marshallward yes we have "ulimit -s unlimited"
In run script, we also have export OMP_STACKSIZE=512M. I just increased this #, seems jobs are running, need to wait for half hour to confirm it.

**Comment by jiandewang** [comment]
@marshallward I increased OMP_STACKSIZE to 800M and the job ran fine

**Comment by marshallward** [comment]
@jiandewang Thanks, that is yet another interesting observation - and also means it's something about OpenMP memory usage.

Maybe we can tackle this with more precise OpenMP directives.  But this probably needs some more investigation and/or discussion.

**Comment by Hallberg-NOAA** [comment]
@gustavo-marques, there are no substantive changes with this PR in `calc_Eady_growth_rate()` where the first differences are being detected, nor in `calc_isoneutral_slopes()` where `dzSxN` is calculated nor in `find_eta()` that could possibly explain these divergences.  Unfortunately what this means is that we do not have enough `chksums` yet to isolate this difference.

To track down this answer change with `chksums`, we would have to add chksums for all the arguments to the call to `calc_isoneutral_slopes()` immediately before the call to `calc_Eady_growth_rate()` in `calc_slope_functions()` in both the current main branch of the code and the new code with this PR, and then keep tracking back through the code to find the original source of the divergence in the NCAR regression tests.

  The other way that we could track down these differences would be by git bisection to isolate the specific commit that changed the answers, but in this case that strategy might be even more work.

@gustavo-marques, if you could point me to the test case where we are getting changes in the regression answers, along with whatever input files we would need to try to reproduce these regressions on NOAA computers, I am available this week to work on tracking down the source of these differences.  Let's coordinate this off-line.

**Comment by Hallberg-NOAA** [comment]
I think that we now know why the answers were changing for the NCAR regression testing (in addition to the other issues already addressed above).

  When we refactored the equations of state to make them elemental, we did not manage to carry forward the actions resulting from the flag `USE_WRIGHT_2ND_DERIV_BUG` that determines whether to correct an error in the expressions for two of the second derivative calculations when `EQN_OF_STATE = "WRIGHT"`.  The run-time parameter is still there and it is being logged, but it does nothing; worse yet, the revised code behaves as though `USE_WRIGHT_2ND_DERIV_BUG = True` although the default is `False`.

  This impacts solutions that use one of the parameterizations enabled with `USE_STANLEY_... = True`, have `EQN_OF_STATE = "WRIGHT"` and do not explicitly set `USE_WRIGHT_2ND_DERIV_BUG = True`.  This slipped through our testing because we do not have any such configurations in the GFDL regression test suite.  We are encouraging people to use `EQN_OF_STATE = "WRIGHT_REDUCED"` if you want something that is mathematically equivalent to `EQN_OF_STATE = "WRIGHT"`, but fixes the 2nd derivative bugs and is refactored with added parentheses so that answers are invariant to levels of optimization or choice of compiler.  There are other equation of state options that also are demonstrably bug-free.  It is only "WRIGHT" that has these problems because we are retaining the ability to generate all of its bugs to be able to recreate older solutions.

  I do have a fix to this that will once again make configurations with `USE_WRIGHT_2ND_DERIV_BUG = False` work as intended, and in tests with a version our our global_ALE test case using the same parameterizations as NCAR's proto-CESM test, it is now giving bitwise identical answers to those that I get with the current dev/ncar fork.  I will be putting this in shortly as a PR directly to `NOAA-GFDL:gfdl-to-main-2024-05-31`.

  We have not gone through the same intensive diagnosis of why EMC's 5x5 test cases are showing answer changes, but hopefully it was tripping up on similar issues to the ones we have debugged with dev/ncar.

**Comment by jiandewang** [comment]
@Hallberg-NOAA for 5x5 we have
USE_WRIGHT_2ND_DERIV_BUG = False
EQN_OF_STATE = "WRIGHT"

see MOM_parameter_doc.all on GAEA: /gpfs/f5/nggps_emc/scratch/Jiande.Wang/For-Marshall/PR0608/5x5

**Comment by Hallberg-NOAA** [comment]
After running a version of our Global-ALE test case with all of the parameter settings from EMC's 5x5 test case, I think that the only thing that we need to do with the new code to reproduce the previous answers with the new code is to set `EPBL_ANSWER_DATE = 20231231`.

**Comment by Hallberg-NOAA** [comment]
The PR fixing the Wright equation of state problems that were changing answers in the NCAR regression suite can be found at https://github.com/NOAA-GFDL/MOM6/pull/686.

**Comment by Hallberg-NOAA** [comment]
Thanks to some persistent work by @jiandewang and others at EMC to track down where the answers diverged, we have a pending update to this PR that finally has all of the EMC regression test cases reproducing their previous answers, along with a second update that would have trapped the problem more quickly.  I believe that there will be no other (known) problems once https://github.com/NOAA-GFDL/MOM6/pull/690 and https://github.com/NOAA-GFDL/MOM6/pull/687 are merged into the branch for this PR.

**Comment by jiandewang** [comment]
special thanks for @DeniseWorthen who provided a key clue (melt_potential) for me and Bob. Otherwise we might still be at struggling stage.

**Comment by jiandewang** [comment]
@Hallberg-NOAA do you plan to merge "checksum melt_potential" in this candidate ? I will do a final full testing (required by UFS and EIB group) after you finalize this.

**Review by jiandewang — APPROVED** [review]
works as expected in UFS now.
adding USE_HUYNH_STENCIL_BUG = True, plus EPBL_ANSWER_DATE=20231231 in 5x5 setting kept current answers

**Review by alperaltuntas — APPROVED** [review]
NCAR tests pass.

**Review by abozec — APPROVED** [review]
COAPS approves.

**Comment by mathomp4** [comment]
Much like @jiandewang, in my testing, GEOSgcm is zero-diff at C12 if I add:
```
USE_HUYNH_STENCIL_BUG = True
EPBL_ANSWER_DATE=20231231
```

I don't have approval rights here it seems, so I guess this is just a 👍🏼

**Review by sanAkel — APPROVED** [review]
@Hallberg-NOAA 

>  Santha, if you still have the permissions to click the "Approve" button on MOM-ocean, I think it would help if you were to do so now that we have Matt's written approval.

Approving it following @mathomp4's test results.

**Pull request merged**
