### PR TITLE
(*)Add parentheses for FMA rotational symmetry

### PR DESCRIPTION
**Pull request by Hallberg-NOAA**
This series of 30 commits adds parentheses in 54 files throughout the MOM6 code base, or (in a few cases) revises the order of sums in expressions for various u- and v-component calculations, so that all answers exhibit rotational symmetry when fused-multiply-adds (FMAs) are enabled and appropriate parameter settings are chosen.

  As a part of these changes, there is a new element `ocean_grid_type%Coriolis2Bu` with the square of the Coriolis parameter in the widely used transparent ocean grid type.

  In order to obtain rotational symmetry (with or without FMAs) for all cases in the NOAA-GFDL MOM6-examples regression suite where FMS supports grid rotation (plus non-Boussinesq versions of these test cases and some extra examples to reflect parameterizations used in CESM prototypes), the following parameter settings may be needed:

```
  #override DEFAULT_ANSWER_DATE = 99991231    ! This gives rotational symmetry if it is higher than 20240701
  #override HOR_DIFF_ANSWER_DATE = 99991231    ! This must be 20240331 or higher for rotational symmetry.
  #override NDIFF_ANSWER_DATE = 99991231    ! This must be 20240331 or higher for rotational symmetry.
  #override WAVE_INTERFACE_ANSWER_DATE = 99991231    ! This must be 20230103 or higher for rotational symmetry.
  #override MEKE_GM_SRC_ANSWER_DATE = 99991231    ! This must be 20240601 or higher for rotational symmetry.

  #override BT_USE_OLD_CORIOLIS_BRACKET_BUG = False
  #override USE_GM_WORK_BUG = False
  #override MEKE_GM_SRC_ALT_SLOPE_BUG = False

  #override USE_OCMIP2_CFC = False    ! The FMS routine atmos_ocn_coupler_flux() does not support grid rotation yet.
```

  Note that FMS does not currently support an eastern, western or southern tripolar grid, so global test cases with a northern tripolar grid can not be tested for rotational symmetry.  However, the Baltic test cases have been used to verify the rotational symmetry of all of the parameterizations that are used in global models.

  Note also that automated grid rotation testing is not supported yet for all types of open boundary conditions or for velocities with ALE sponges.

  All answers are bitwise identical when FMAs are not enabled, but answers do change when FMAs are enabled.  The only change in public interfaces is the addition of a new squared Coriolis parameter element in the transparent ocean grid type.  The list of commits in this PR include:

- NOAA-GFDL/MOM6@fd82861e3 (*)Add parentheses in end_value_h4 for FMAs
- NOAA-GFDL/MOM6@ffa766b45 (*)More parentheses in density integrals for FMAs
- NOAA-GFDL/MOM6@e810ac537 (*)Parenthesize tracer_advect PPM edge values
- NOAA-GFDL/MOM6@182223c50 (*)Parenthesize diagnostics for FMAs
- NOAA-GFDL/MOM6@44f1130fc (*)Parenthesize parameterization squares for FMAs
- NOAA-GFDL/MOM6@fc2af28ed (*)Parenthesize initialization squares for FMAs
- NOAA-GFDL/MOM6@ffef92f7f (*)Parenthesize MOM_hor_visc for FMAs
- NOAA-GFDL/MOM6@6216fa1f5 (*)Parenthesize MOM_lateral_mixing_coeffs for FMAs
- NOAA-GFDL/MOM6@46e8b661e (*)Parenthesize MOM_barotropic for FMAs
- NOAA-GFDL/MOM6@64b851c4e (*)Parenthesize CorAdCalc for FMAs
- NOAA-GFDL/MOM6@f0c52ddb1 (*)Parenthesize MOM_set_diffusivity for FMAs
- NOAA-GFDL/MOM6@0b50a155a (*)Rearrange calc_kappa_shear_vertex for FMAs
- NOAA-GFDL/MOM6@c0bef189a (*)Parenthesize set_viscous_ML for FMAs
- NOAA-GFDL/MOM6@ebf02a97a (*)Parenthesize find_uv_at_h for FMAs
- NOAA-GFDL/MOM6@654cd4aab (*)Parenthesize MOM_internal_tides for FMAs
- NOAA-GFDL/MOM6@03dc6f9a5 (*)Parenthesize Zanna_Bolton for FMAs
- NOAA-GFDL/MOM6@49419f732 (*)Parenthesize thickness_diffuse for FMAs
- NOAA-GFDL/MOM6@56d053a04 +(*)Add and use G%Coriolis2Bu
- NOAA-GFDL/MOM6@5398e6fdf (*)Parenthesize CoriolisStokes and LA_Stk for FMAs
- NOAA-GFDL/MOM6@b2beab215 (*)Parenthesize iceberg_forces for FMAs
- NOAA-GFDL/MOM6@c344a117f (*)Parenthesize tracer_hordiff for FMAs
- NOAA-GFDL/MOM6@ce559ce64 (*)Parenthesize MOM_calc_varT for FMAs
- NOAA-GFDL/MOM6@307a4e2e5 (*)Parenthesize calc_isoneutral_slopes for FMAs
- NOAA-GFDL/MOM6@99fd95796 (*)Parenthesize PressureForce_Montgomery for FMAs
- NOAA-GFDL/MOM6@8066a3da0 (*)Simplify density integral parentheses
- NOAA-GFDL/MOM6@24091ccf0 (*)Add parentheses to 4 EOS int_density routines
- NOAA-GFDL/MOM6@9172cd576 (*)Add parentheses for density_integrals with FMAs
- NOAA-GFDL/MOM6@4f710efb0 (*)Add parentheses for oblique OBCs with FMAs
- NOAA-GFDL/MOM6@f0e61f30c (*)Parenthesize continuity_PPM curv_3 expressions
- NOAA-GFDL/MOM6@6628dbff5 (*)Parenthesize squares of wind stresses for FMAs

### CODE REVIEW

**Review by kshedstrom — APPROVED** [review]
I approve this PR, but I have a question. Before turning on FMAs, answers did not change. With FMAs, answers do change, but the unit_tests fail. Is there a way to get it to behave with FMAs?
```
 The values of WRIGHT drho_dT_dT disagree.  -1.1402818751119733E-02 and  -7.2448371221038111E-03 differ by  -4.15798163E-03 ( -4.46E-01), tol=  3.11848682E-04
   k        Calculated value           Correct value remap_via_sub_cells() 2
   1  1.0000000000000002E+01  1.0000000000000000E+01 err=  1.7763568394002505E-15 <--- WRONG
   2  5.9999999999999982E+00  6.0000000000000000E+00 err= -1.7763568394002505E-15 <--- WRONG
   3  2.0000000000000004E+00  2.0000000000000000E+00 err=  4.4408920985006262E-16 <--- WRONG
   4 -2.0000000000000004E+00 -2.0000000000000000E+00 err= -4.4408920985006262E-16 <--- WRONG
   5 -5.9999999999999982E+00 -6.0000000000000000E+00 err=  1.7763568394002505E-15 <--- WRONG
   6 -1.0000000000000002E+01 -1.0000000000000000E+01 err= -1.7763568394002505E-15 <--- WRONG
   k        Calculated value           Correct value remap_via_sub_cells() 3
   1  1.1500000000000005E+01  1.1500000000000000E+01 err=  5.3290705182007514E-15 <--- WRONG
   2  1.0500000000000002E+01  1.0500000000000000E+01 err=  1.7763568394002505E-15 <--- WRONG
   4  8.4999999999999982E+00  8.5000000000000000E+00 err= -1.7763568394002505E-15 <--- WRONG
   5  7.4999999999999973E+00  7.5000000000000000E+00 err= -2.6645352591003757E-15 <--- WRONG
   6  6.4999999999999929E+00  6.5000000000000000E+00 err= -7.1054273576010019E-15 <--- WRONG
   k        Calculated value           Correct value remap_via_sub_cells() 4
   2 -1.0500000000000004E+01 -1.0500000000000000E+01 err= -3.5527136788005009E-15 <--- WRONG
   3 -1.2000000000000007E+01 -1.2000000000000000E+01 err= -7.1054273576010019E-15 <--- WRONG
Failed tests:   1   3   4   5   
First failed test: attic remapping unit tests
remapping_unit_tests : FAILED
```

**Comment by kshedstrom** [comment]
I should add that this is gfortran on chinook. I read online that the way to turn on FMAs is with ` -ftree-vectorize -ffast-math -march=native`.

**Comment by marshallward** [comment]
Don't use `-ffast-math`, this turns on a whole load of unreproducible options that we don't want to use.  I also don't think you need `-ftree-vectorize`.  (I had never heard of it until you mentioned it.)

You should just first try `-mfma`.  After that, you can also consider
* `-mavx -mfma` (add AVX instructions)
* `-O2 -mavx -mfma` (with optimization)
* `-O2 -march=core-avx2 -mavx -mfma` (with full x86 AVX2 instruction set)

(You might also try `-march=native` in place of `core-avx2`.)

At the very least, I would be prepared for different answers from each of those tests.  But perhaps they will pass your unit tests.

**Review by mathomp4 — APPROVED** [review]
Well, I guess the GMAO flags are boring enough that this was a zero-diff change for us. Nice simple approve.

**Review by abozec — APPROVED** [review]
COAPS approves.

**Comment by jiandewang** [comment]
I am in the processing of merging previous (2024-05-31) PR to dev/emc and UFS repository, please allow me a bit delay on testing this PR.

**Comment by Hallberg-NOAA** [comment]
We also had some imperfect vertical remapping unit-tests when FMAs are enabled.  I have added one more commit with parentheses in part of the ALE remapping code that give us unit tests that all pass with FMAs for the intel compiler version we are using at GFDL.  However, I don't know whether this will also fix the roundoff-level vertical remapping unit-test anomalies that @kshedstrom was finding with gfortran on Chinook, which seem more extensive that what I was finding with the intel compiler.

**Review by alperaltuntas — APPROVED** [review]

**Comment by jiandewang** [comment]
tested on 4 non-wcoss machines and got b4b results. Testing on wcoss now, shall have updating tomorrow. Sorry for delayed response here (which is caused by the combination of many unexpected factors that are out of my control).

**Comment by jiandewang** [comment]
all UFS testing on wcoss failed to match current existing baseline (as expected), difference are small enough

**Review by jiandewang — APPROVED** [review]
works as expected. No change on non-wcoss machine, minor change on wcoss

**Comment by Hallberg-NOAA** [comment]
This PR has been evaluated and approved by representatives of the requisite 5 primary development branches (in addition to the implicit approval from the initiating primary development branch).

**Pull request merged**
