### PR TITLE
GFDL to main 2022-10-27

### PR DESCRIPTION
**Pull request by marshallward**
This pull request includes several major new features, along with the usual
batch of bugfixes and code improvements.

Major features include:

* Support for tidal self-attraction and loading

* Layer interface filtering

* Improved support for wind stress in mixed layers, especially with respect to
  vertical viscosity.

* Control of channel drag thickness layers

Along with these features are many new configuration parameters.

Bug fixes include the following: tracers in the ALE sponge, ice shelf
initialization, OBC tracer nudging, predictor timestep restart field handling,
split-timstep diagnostics, and oblique OBCs.

**Note to reviewers**:

Several parameters have new default values, which can potentially change
answers.  These include parameters which may have been previously unconfigured.
Please review the parameters listed below, and compare to your existing
`MOM_parameter_doc.all` files.

Detailed descriptons for each change are available in the pull request
comments.

----

Features
- NOAA-GFDL/MOM6#192
- NOAA-GFDL/MOM6#195
- NOAA-GFDL/MOM6#201
- NOAA-GFDL/MOM6#210

Bugfixes
- NOAA-GFDL/MOM6#188
- NOAA-GFDL/MOM6#190
- NOAA-GFDL/MOM6#194
- NOAA-GFDL/MOM6#205
- NOAA-GFDL/MOM6#209
- NOAA-GFDL/MOM6#219

Misc
- NOAA-GFDL/MOM6#193
- NOAA-GFDL/MOM6#196
- NOAA-GFDL/MOM6#200
- NOAA-GFDL/MOM6#202
- NOAA-GFDL/MOM6#204
- NOAA-GFDL/MOM6#206
- NOAA-GFDL/MOM6#207
- NOAA-GFDL/MOM6#211
- NOAA-GFDL/MOM6#213
- NOAA-GFDL/MOM6#214
- NOAA-GFDL/MOM6#218

Contributors:
  - @Hallberg-NOAA: 9
  - @marshallward: 5
  - @herrwang0: 2
  - @WenhaoChen89: 2
  - @kshedstrom: 1
  - @MJHarrison-GFDL: 1
  - @StephenGriffies: 1

New Parameter Defaults
  - KAPPA_SHEAR_VERTEX_PSURF_BUG: True -> False
  - BAROTROPIC_TIDAL_SAL_BUG: True -> False
  - LAYER_Z_INIT_IC_EXTRAP_BUG: True -> False

Added to MOM_parameter_doc.all:
  - APPLY_INTERFACE_FILTER
    - INTERFACE_FILTER_TIME
    - INTERFACE_FILTER_MAX_CFL
    - INTERFACE_FILTER_ORDER
    - INTERFACE_FILTER_ISOTROPIC
  - KV_ML_INVZ2
  - TIDAL_SAL_SHT
  - SUBGRID_TOPO_AT_VEL
  - KD_ML_TOT
  - CHANNEL_DRAG_MAX_BBL_THICK
  - USE_POROUS_BARRIER
  - PORBAR_ANSWER_DATE
  - FIXED_DEPTH_LOTW_ML
  - PORBAR_ETA_INTERP
  - VON_KARMAN_CONST
  - PORBAR_MASKING_DEPTH
  - LOTW_VISCOUS_ML_FLOOR
  - KV_EXTRA_BBL
  - VON_KARMAN_BBL
  - STORE_CORIOLIS_ACCEL

Removed from MOM_parameter_doc.all:
  - KDML
  - HENYEY_IGW_BACKGROUND_NEW
  - KVBBL
  - KVML

Added to MOM_parameter_doc.short:
  - KV_ML_INVZ2

Removed from MOM_parameter_doc.short:
  - KAPPA_SHEAR_VERTEX_PSURF_BUG
  - BAROTROPIC_TIDAL_SAL_BUG
  - LAYER_Z_INIT_IC_EXTRAP_BUG
  - KVML

### CODE REVIEW

**Comment by marshallward** [comment]
The regressions are due to changes in the default parameters, and can be overridden.

**Review by kshedstrom — APPROVED** [review]
I approve this PR.

**Comment by jiandewang** [comment]
default value for KVML is changed from 1E-4 to 0, set KVML=1E-4 will be the same as KV_ML_INVZ2=1E-4. Just wan to confirm it.

**Comment by marshallward** [comment]
> default value for KVML is changed from 1E-4 to 0, set KVML=1E-4 will be the same as KV_ML_INVZ2=1E-4. Just wan to confirm it.

Yes, that's right.  If `KV_ML_INVZ2` is unset (or set to a negative number for some reason), then `KVML` is enabled and used in its place.

I'm not sure how the original default value worked, but it may have been from `KV`.

**Review by abozec — APPROVED** [review]
COAPS approves the changes

**Comment by jiandewang** [comment]
works fine with intel compiler but job crashed with gnu compiler at
https://github.com/NOAA-GFDL/MOM6/blob/dev-gfdl-candidate-main-2022-10-27/src/parameterizations/lateral/MOM_spherical_harmonics.F90#L298
with error: Fortran runtime error: Attempt to DEALLOCATE unallocated 'cs'

However, when compiled with extra DEBUG flags under gnu, job finished fine, see UFS DEBUG flag at
https://github.com/ufs-community/ufs-weather-model/blob/develop/cmake/GNU.cmake#L13

@marshallward I put the run log on GAEA at /lustre/f2/dev/ncep/Jiande.Wang/For-Marshall, see line 160

**Comment by marshallward** [comment]
Thanks @jiandewang I've looked at the code and I think it makes sense.

These lines appear in `tidal_forcing_init()`:
https://github.com/mom-ocean/MOM6/blob/84682aae1f3ccbbd3906413f4048c386b05e3118/src/parameterizations/lateral/MOM_tidal_forcing.F90#L278-L281

If `TIDES` is false then the fields in `sht_CS` are never allocated.

(BTW this check is perhaps redundant, since there is another `TIDES` check in the RK2 solver.  But either way, `sht_CS` is not initialized if `TIDES` is false.)

However, there is no similar check around `tidal_forcing_end()` or `spherical_harmonics_end()`.

----

There are a few ways to fix it, probably the simplest is to just add `if (allocated())` checks to `spherical_harmonics_end()`.  If I were doing it, I would probably add the `use_tides` logical to either the RK2 CS or the tidal forcing CS and use that to decide whether or not to call `spherical_harmonics_end()`.

This code is from @herrwang0 so he may have an opinion on how to fix this.

**Comment by herrwang0** [comment]
It does look like there is a missing `use_tides` check in subroutine `end_dyn_split_RK2`, compared with `initialize_dyn_split_RK2`
https://github.com/mom-ocean/MOM6/blob/84682aae1f3ccbbd3906413f4048c386b05e3118/src/core/MOM_dynamics_split_RK2.F90#L1342-L1348

https://github.com/mom-ocean/MOM6/blob/84682aae1f3ccbbd3906413f4048c386b05e3118/src/core/MOM_dynamics_split_RK2.F90#L1704-L1706

I agree with Marshall, adding `use_tides` check to  `end_dyn_split_RK2` should fix the bug and make it consistent with the init call. Adding  `if allocated()` checks to the variables in `spherical_harmonics_end()`is also good to me (and again it is consistent with `tidal_forcing_end()`).  So either (or both) is fine with me. 

---
Side points:
1. Related to this, I find that there are probably a bunch of `end` calls missing in the unsplit dynamical cores, say e.g.
https://github.com/mom-ocean/MOM6/blob/84682aae1f3ccbbd3906413f4048c386b05e3118/src/core/MOM_dynamics_unsplit.F90#L713-L722

2. Also, I wonder what is the general option on the `initialized` flag is nowadays? I suppose we could use it in the `_end()` routines to be more defensive and able to expose bugs like this (when `end` routines are erroneously called).
```Fortran
If (.not. CS%initialized) call MOM_error(FATAL, ...)
```

**Comment by marshallward** [comment]
@jiandewang I have a PR which hopefully fixes this issue.  https://github.com/NOAA-GFDL/MOM6/pull/230
@herrwang0 if you want to test or review that would be helpful.

As for the questions above: 
* I think there are still significant gaps in the "finalize" usage.  I did a valgrind check some time ago and caught many of them, but no doubt there are many more unresolved.  I would also like to see these handled by `final` procedure language feature, but unfortunately it's not well-supported at the moment.

* I don't personally support the `initialized` flag checks, and would rather this state be determined this the configuration logic of the run, but I think there's still quite a few around being used for important checks.  Some have replaced older `associated()` checks from when these were pointers.

**Comment by jiandewang** [comment]
> @jiandewang I have a PR which hopefully fixes this issue. [NOAA-GFDL#230](https://github.com/NOAA-GFDL/MOM6/pull/230) @herrwang0 if you want to test or review that would be helpful.
> 
> As for the questions above:
> 
> * I think there are still significant gaps in the "finalize" usage.  I did a valgrind check some time ago and caught many of them, but no doubt there are many more unresolved.  I would also like to see these handled by `final` procedure language feature, but unfortunately it's not well-supported at the moment.
> * I don't personally support the `initialized` flag checks, and would rather this state be determined this the configuration logic of the run, but I think there's still quite a few around being used for important checks.  Some have replaced older `associated()` checks from when these were pointers.

@marshallward the fixing works fine in UFS

**Review by sanAkel — APPROVED** [review]

**Review by gustavo-marques — APPROVED** [review]
NCAR approves this PR.

**Comment by marshallward** [comment]
This looks ready to merge.  Thank you as always for the verification.

**Pull request merged**
